const ATTEMPT_STORE_FETCHING_DATA = "ATTEMPT_STORE_FETCHING_DATA";
const STORE_FETCHING_DATA = "STORE_FETCHING_DATA";
const STORE_FETCHING_DATA_FAILURE = "STORE_FETCHING_DATA_FAILURE";
const STORE_FETCHING_DATA_SUCCESS = "STORE_FETCHING_DATA_SUCCESS";

const storeInFirebase = (state) => ({
    type: ATTEMPT_STORE_FETCHING_DATA,
    payload:state
  });
    
export {
    ATTEMPT_STORE_FETCHING_DATA,
    STORE_FETCHING_DATA,
    STORE_FETCHING_DATA_FAILURE,
    STORE_FETCHING_DATA_SUCCESS,
    storeInFirebase,
};