const ATTEMPT_LOGIN_FETCHING_DATA = "ATTEMPT_LOGIN_FETCHING_DATA";
const LOGIN_FETCHING_DATA = "LOGIN_FETCHING_DATA";
const LOGIN_FETCHING_DATA_FAILURE = "LOGIN_FETCHING_DATA_FAILURE";
const LOGIN_FETCHING_DATA_SUCCESS = "LOGIN_FETCHING_DATA_SUCCESS";

const loginUserInFirebase = (state) => ({
    type: ATTEMPT_LOGIN_FETCHING_DATA,
    payload:state
  });
    
export {
    ATTEMPT_LOGIN_FETCHING_DATA,
    LOGIN_FETCHING_DATA,
    LOGIN_FETCHING_DATA_FAILURE,
    LOGIN_FETCHING_DATA_SUCCESS,
    loginUserInFirebase,
};