const ATTEMPT_FIREBASE_CREATE_USER_DATA = "ATTEMPT_FIREBASE_CREATE_USER_DATA";
const FETCHING_DATA = "FETCHING_DATA";
const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";
const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";

const registerUserInFirebase = (state) => ({
    type: ATTEMPT_FIREBASE_CREATE_USER_DATA,
    payload:state
  });
    
export {
  ATTEMPT_FIREBASE_CREATE_USER_DATA,
    FETCHING_DATA,
    FETCHING_DATA_FAILURE,
    FETCHING_DATA_SUCCESS,
    registerUserInFirebase,
};